App\Entity\Location:
  properties:
    city:
      - NotBlank: ~
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [new, edit]
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [new, edit]

App\Entity\Forecast:
  properties:
    temperature:
      - Range:
          min: -100
          max: 100
          groups: [new, edit]
    wind:
      - Range:
          min: 1
          max: 180
          groups: [new, edit]
    date:
      - Date: ~